### ISSUE TITLE
Opening single connection for persistence causing issues

### ISSUE THREAD

**Issue by dpachala** [pip-services3-dotnet/pip-services3-postgres-dotnet#1]
Hello, 

There is an issue with the current architecture for handling connections. When the connection component initializes, it creates one connection for the lifetime of the component. This causes a few issues. If the connection ever gets into an error state, you can't recover from it. Connection pooling can't be used because the the connection is never released and a single connection can easily get overwhelmed with many requests.

I do see that there is an open and close async in postgres persistence but i dont believe this will fix all the issues, I can use it to close and reopen the connection when it does get error'd but it still doesnt solve that it's using one connection for all the calls. There are other issues that opening and closing the connection will lead to which makes me think that it wasnt made for the purpose Im thinking of.

Am I thinking about this correctly? Or am I using the postgresconnection component incorrectly?

Thanks

**Comment by kuznetsov-denis** [comment]
@dpachala 
Hello!

You’re totally right, in version 3.3.2 we changed the approach to using connections, now each time a request is executed, a new NpgsqlConnection is created and opened (selected from the pool) and released after the request is completed (returned to the pool).

Thank you for your time and consideration.
